Wrap in Python
Wave-View-Imaging/citi pull request #18
Opened 2021-07-12 23:20 UTC by Besler

2021-07-12 23:31 UTC, Besler commented
I based most of this development off these references:
- https://depth-first.com/articles/2020/08/03/wrapping-rust-types-as-python-classes/
- https://pypi.org/project/setuptools-rust/

2021-08-15 22:43 UTC, justkash requested changes
I think the biggest thing to do would be to add error handling support for the python side. You can rebase with the changes from PR #19.

2021-08-15 22:43 UTC, justkash commented on ffi/python/citi/record.py
> +'''Record implemented through a foreign function interface
PR #19 adds support for error handling through the ffi that can be take advantage of on the python side.

2021-08-15 22:43 UTC, justkash commented on src/ffi.rs
> +//! Foreign Function Interface
For your reference, PR #19 makes all the changes mentioned in the comments and it also adds a few extra functions for modifying citi::Record through the ffi.

2021-10-04 20:39 UTC, closed without merging